version: '3'

services:
  backend:
    container_name: backend-server
    image: dockerhub_id/app-with-actions:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: rds:3306/app?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
